export const ACTIONS = {
	NEXT_PAGE: 'NEXT_PAGE',
	PREV_PAGE: 'PREV_PAGE',

	SET_USERS: 'SET_USERS',
	SET_USERS_META: 'SET_USERS_META',

	SET_POSTS: 'SET_POSTS',
	SET_POSTS_META: 'SET_POSTS_META',

	SET_TODOS: 'SET_TODOS',
	SET_TODOS_META: 'SET_TODOS_META',

	SET_COMMENTS: 'SET_COMMENTS',
	SET_COMMENTS_META: 'SET_COMMENTS_META',

	TOGGLE_COMMENTS: 'TOGGLE_COMMENTS',
	TOGGLE_ADD_USER: 'TOGGLE_ADD_USER',
};
